### ISSUE TITLE
Error Inflating

### ISSUE THREAD

**Issue by whowazit** [hdodenhof/CircleImageView#100] opened 2016-01-05 03:12 UTC
I keep getting error inflating when running the project but in the preview (xml) it's displaying fine. How to fix this?

**Comment by ahmedoid** [comment] 2016-01-11 14:07
+1

**Comment by hdodenhof** [comment] 2016-01-30 17:01
Could you please provide more details about the exception and some code samples for further investigation? Thanks.

**Comment by tristanrichard** [comment] 2016-03-09 14:26
W/System.err: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class de.hdodenhof.circleimageview.CircleImageView
03-09 15:24:11.084 29477-29477/com.soudfa W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
03-09 15:24:11.084 29477-29477/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
03-09 15:24:11.084 29477-29477/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
03-09 15:24:11.085 29477-29477/? W/System.err:     at android.view.View.inflate(View.java:19790)
03-09 15:24:11.085 29477-29477/? W/System.err:     at com.soudfa.Fragments.Conversation.Views.ParticipantChatRow_.onFinishInflate(ParticipantChatRow_.java:57)
03-09 15:24:11.085 29477-29477/? W/System.err:     at com.soudfa.Fragments.Conversation.Views.ParticipantChatRow_.build(ParticipantChatRow_.java:42)
03-09 15:24:11.085 29477-29477/? W/System.err:     at com.soudfa.Fragments.Conversation.Adapter.ConversationListAdapter.getView(ConversationListAdapter.java:77)
03-09 15:24:11.085 29477-29477/? W/System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2346)
03-09 15:24:11.085 29477-29477/? W/System.err:     at android.widget.ListView.measureHeightOfChildren(ListView.java:1281)

**Comment by andiinsanudin** [comment] 2016-03-18 09:51
Hello @tristanrichard,  just remove android:adjustViewBounds="true"

**Comment by cloud143** [comment] 2016-04-26 07:51
thanks @andiinsanudin

**Comment by hseirwilliam** [comment] 2016-05-01 14:32
I solved the problem (in my case) by removing another "compile ..." line in gradle dependencies.
The root cause of my case may lead to "http://developer.android.com/intl/zh-tw/tools/building/multidex.html".

**Comment by hdodenhof** [comment] 2016-05-01 15:14
Duplicate of #96.

**Closed by hdodenhof** 2016-05-01 15:14 UTC

**Comment by iamerrorist** [comment] 2017-07-26 19:07
I copied some layout and fragment and an icon from another project. So, in my case it was just wrong placing the icon image! when I pasted it to drawable, I didn't notice ".../drawable-v21" in the confirm dialog. AndroidStudio was just keep repeating "Error inflating class de.hdodenhof.circleimageview.CircleImageView". It takes about 2 hours for me to find it! Anyway...

**Comment by varotariyavm** [comment] 2018-07-26 13:49
i removed android:scaleType="fitCenter" line from imageview xml and its working
