### ISSUE TITLE
Request: ability to temporary disable rounding the images

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [hdodenhof/CircleImageView#111] opened 2016-02-25 12:07 UTC
In some cases, instead of a circular image, I wish to show a normal image in the same area that the CircleImageView takes.
It would be nice to be able to have a "setOval(boolean)" function, which will enable&disable making the content of the CircleImageView to be rounded.
This is better than having a container of it together with a normal ImageView.

Not only that, but for drawables that exist as XML files (even those that are already round), it would be better to disable the rounding of them, instead of creating new bitmaps using getBitmapFromDrawable .

**Comment by hdodenhof** [comment] 2016-02-25 12:26
Duplicate of https://github.com/hdodenhof/CircleImageView/pull/33. I'll leave this open for now and might reconsider.

**Comment by AndroidDeveloperLB** [comment] 2016-02-25 12:38
Thank you. This can be useful for avoiding creation of bitmaps, especially for the easy cases where I can create a circle drawable myself

**Comment by jonasborggren** [comment] 2016-03-14 11:23
+1

**Comment by AlexBravo** [comment] 2016-04-27 16:18
+1

**Comment by AlexBravo** [comment] 2016-04-27 16:35
Henning, disabling CircleImageView would be useful as a debugging feature. 
With this, a developer would not have to change all xml files from CircleImageView to ImageView.

Case to consider:
I'm debugging Picasso right now, which displays its debug indicators in the corner, which is hidden by CircleImageView. So I want to disable CircleImageView together with enabling Picasso debugging in my code.

**Comment by jonasborggren** [comment] 2016-04-28 08:11
In my case this would be useful for when an adapter is using the same view for slightly different rows.
In this case its basically for when **image 1** is for a **user image** and **image 2** is for a **thumbnail**.

Plus, I agree with above arguments as well. When using for example Cloudinary for making images return circular or a specific size it would be nice to be able to see exactly what's going on.

**Comment by hdodenhof** [comment] 2016-05-01 15:58
A snapshot build of 2.1.0 with an option to disable the circular transformation is now available in the Sonatype snapshots repository.

**Comment by AndroidDeveloperLB** [comment] 2016-05-01 16:01
Is it possible to use via gradle?

**Comment by hdodenhof** [comment] 2016-05-01 16:11
```
repositories {
  ...
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

dependencies {
  compile 'de.hdodenhof:circleimageview:2.1.0-SNAPSHOT'
}

```

**Comment by hdodenhof** [comment] 2016-08-06 08:41
Version 2.1.0 with this has been released.

**Closed by hdodenhof** 2016-08-06 08:41 UTC
Labels: enhancement
