### ISSUE TITLE
use imageloader load picture appear black border

### ISSUE THREAD

**Issue by t2314862168** [hdodenhof/CircleImageView#108] opened 2016-02-19 03:23 UTC
@hdodenhof 
my case is : enter Activity use imageloader to load testUrl_1 for CircleImageView , then use imageloader to load testUrl_2 for CircleImageView over and over again , then the CircleImageView appears black border.
my code is :

``` java
public static void displayImageAndInvalidate(String uri, ImageView imageView) {
        ImageAware imageAware = new ImageViewAware(imageView, false);
        ImageLoader.getInstance().displayImage(uri, imageAware,
                getCustomOptions());
// use invalidate , does't work
        imageView.invalidate();
    }
```

if Activity through onPause , then enter Activity , black border disappear,but if i operate change url ,it also .appear black border.
I don't why it happened , sorry for my bad english and please help me!!!

**Comment by hdodenhof** [comment] 2016-02-24 19:41
I'm sorry, but I don't quite understand the events leading to your issue. Could you provide screenshots or a screencast?

**Comment by t2314862168** [comment] 2016-02-25 02:38
@hdodenhof 
if i change the url many times ,the problem can appear,and the screenshots is below
![qq 20160225103027](https://cloud.githubusercontent.com/assets/6425339/13308070/3300e8d4-dbab-11e5-9d1a-f1647e6921fe.png)
the normal is below
![qq 20160225103111](https://cloud.githubusercontent.com/assets/6425339/13308072/4561b76a-dbab-11e5-89ba-8e178aeb9c9e.png)

and i find the solution , my code is :
```java
public static void displayImageAndInvalidate(String uri,
			final ImageView imageView) {
		ImageAware imageAware = new ImageViewAware(imageView, false);
		ImageLoader.getInstance().displayImage(uri, imageAware,
				getCustomOptions(), new SimpleImageLoadingListener() {
					@Override
					public void onLoadingComplete(String imageUri, View view,
							Bitmap loadedImage) {
						// add this for the reason
						imageView.setImageBitmap(null);
						imageView.setImageBitmap(loadedImage);
					}
				});
	}
```
before ``` setImageBitmap(loadedImage) ``` add ``` setImageBitmap(null) ```
but i did't know why it happened.

**Comment by raiarainne** [comment] 2017-07-02 15:29
I can see this issue when i use Picasso or Glide.
And I set image Url in this image vi
![screenshot_2017-07-02-21-43-20](https://user-images.githubusercontent.com/22143915/27771255-f6b5e46c-5f7d-11e7-84dc-70cd8315cc0d.png)
ew.
And this is my code part.
Picasso.with(this).load(imageurl).centerInside().placeholder(R.drawable.photo).noFade().fit().into(profileimage);

Sorry for my bad english.
Please give me solution of this issue

**Comment by raiarainne** [comment] 2017-07-04 14:35
I found the reason of this issue in my case.
This issue was be occurred when i added click event on this image view.
And also i found solution from following link.
https://github.com/hdodenhof/CircleImageView/issues/153
if you check this solution carefully, you will solve your issue.
I hope this will be help you.
Thank you.

**Comment by hdodenhof** [comment] 2017-09-29 13:28
Closing this as the original issue is most likely resolved by now (sorry for not getting back at all) and I can't reproduce it. Please reopen, if this still is an issue.

**Closed by hdodenhof** 2017-09-29 13:28 UTC
