### ISSUE TITLE
How to Set Image from URL.

### ISSUE THREAD

**Issue by madhavkate** [hdodenhof/CircleImageView#224] opened 2017-08-22 17:46 UTC
How to Set Image from URL.. Please Tell Me...When Im using picaso 

Picasso.with(activity).load"my image Url here").noFade().into(profile_photo1);

the App going to Crash

**Comment by hdodenhof** [comment] 2017-08-22 17:56
Duplicate of #222.

**Closed by hdodenhof** 2017-08-22 17:56 UTC
