### ISSUE TITLE
Error:(23, 13) Failed to resolve: de.hdodenhof:circleimageview:2.0.0

### ISSUE THREAD

**Issue by nileshlg2003** [hdodenhof/CircleImageView#92] opened 2015-11-16 08:11 UTC
Hi,
I am having failed to resolved error in my android studio project,
here's my build.gradle settings,

```
apply plugin: 'com.android.application'
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.0'
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "my.package.name.appname"
        minSdkVersion 9
        targetSdkVersion 23
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    compile files('src/main/Vuforia.jar')
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:design:23.1.0'
    compile 'de.hdodenhof:circleimageview:2.0.0'
}
```

**Comment by hdodenhof** [comment] 2015-11-16 08:27
Is jcenter configured in your root build.gradle?

```
allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by nileshlg2003** [comment] 2015-11-16 09:07
this is my project's  build.gradle,

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

```

**Comment by nileshlg2003** [comment] 2015-11-16 09:42
other dependencies are installing correctly, only this one is not installing.

**Comment by hdodenhof** [comment] 2015-11-16 09:48
That's strange! Could you please try the following:
1. Replace `jcenter()` with `mavenCentral()` in the `allprojects` block
2. Change the `CircleImageView`version to 1.3.0 (while keeping `jcenter()`)

Thanks!

**Comment by nileshlg2003** [comment] 2015-11-16 09:52
Tried your suggestion, same problem.
project's build.gradle,
```
allprojects {
    repositories {
        mavenCentral()
    }
```
module's gradle
```
dependencies {
    compile files('src/main/Vuforia.jar')
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:design:23.1.0'
    compile 'de.hdodenhof:circleimageview:1.3.0'

}
```

**Comment by hrhktkbzyy** [comment] 2016-01-08 16:12
I met the same issue just now, and this is the solution, hope it helps:
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

**Comment by djr-jsr** [comment] 2016-01-17 09:18
Having the same problem. Tried all the above but didn't help.

**Comment by hdodenhof** [comment] 2016-01-30 11:32
I'm not sure what's going on here, but to me it looks like problem with your local setups. All `CircleImageView` artifacts are available on Maven Central and Bintray / jCenter. A fallback(!) would be using jitpack.io with `compile 'com.github.hdodenhof:CircleImageView:v2.0.0'`.

**Comment by tarikyurtlu** [comment] 2016-02-01 21:12
Hi @hdodenhof  I have same problem.  I am using **com.github.hdodenhof:CircleImageView:v2.0.0**

**Comment by Cairgy** [comment] 2016-03-03 15:40
I just had the same problem and came here after about 15minutes, the problem was fixed while still reading this solutions. I can only suspect the internet.

**Comment by kamalsint** [comment] 2016-04-19 13:35
I am using this same library but i am getting this error Caused by: java.lang.ClassNotFoundException: Didn't find class "de.hdodenhof.circleimageview.CircleImageView". It was working perfectly but all of a sudden i dont know what happened it is not working. It is compiling properly but during run it is crashing.  So sick of this error. Pls help.

Thanks in advance.

**Comment by hdodenhof** [comment] 2016-04-19 13:43
@kamalsint Your problem is unrelated to this issue. Please create a new one and provide more details about your setup.

**Comment by zohabAli** [comment] 2016-05-05 13:37
I was getting this error "Failed to resolve: de.hdodenhof:circleimageview:2.0.0"
Problem was in my internet. I have to use proxy for internet in my college.....and when I disabled the proxy.....guess what, problem solved ! :)

**Comment by akritikts** [comment] 2016-06-16 20:03
Same problem. Tried all the above solutinos but did not work.

**Comment by akritikts** [comment] 2016-06-16 20:03
Same problem. Tried all the above solutions but did not work.

**Comment by alirezafathi84** [comment] 2016-07-26 11:55
Go to Files-->Settings--> Gradle 
Select "Use default gradle wrapper(recommended)
AND UNCHECK "Offline work" Check box

**Comment by Payhood** [comment] 2016-07-26 11:58
Go to Files-->Settings--> Gradle 
Select "Use default gradle wrapper(recommended)
AND UNCHECK "Offline work" Check box

**Comment by songzhiye** [comment] 2016-11-24 15:07
Same problem. Tried all the above solutions but did not work. Android Studio version is 2.2 Once I guess someting was wrong to my internet, but when I tried the address https://jcenter.bintray.com in my browser,   I found it was fluent. So who can help me?

**Comment by shaojunlv** [comment] 2016-12-13 09:23
thx ,it helps me.

**Comment by iniostime** [comment] 2017-08-21 04:07
it's works, 1.5.0

    compile 'com.github.ksoichiro:android-observablescrollview:1.5.0'

**Comment by hdodenhof** [comment] 2017-09-29 09:06
Closing this as it's not an issue with this lib but some local hickup.

**Closed by hdodenhof** 2017-09-29 09:06 UTC

**Comment by dhriteshpatel** [comment] 2017-12-03 08:57
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
its working thanks for help

**Comment by DroidMagician** [comment] 2018-10-22 06:48
Please kindly check if your studio is in Offline mode or not if yes then disable Offline mode and then try again.
Thanks

**Comment by AliAndArdDev** [comment] 2020-08-26 19:37
I had the same problem while repositories block in project level build.gradle was including the jitpack.io . I just fixed the issue by setting up a vpn and every thing woks fine. I hope it helps!
