### ISSUE TITLE
Showing black background.

### ISSUE THREAD

**Issue by maheshsuthar93** [hdodenhof/CircleImageView#282] opened 2018-08-08 06:31 UTC
I am using this library and when i set image using picasso image shows black background and when i resume app and open again it goes.

**Comment by hdodenhof** [comment] 2018-08-17 13:46
Are you using `LAYER_TYPE_SOFTWARE`?

**Comment by maheshsuthar93** [comment] 2018-08-17 15:51
Yes but not working this.

**Comment by hdodenhof** [comment] 2018-08-17 16:30
Well, you shouldn't use that.

**Comment by maheshsuthar93** [comment] 2018-08-18 08:44
How can i resolve that issue?

**Comment by hdodenhof** [comment] 2018-08-18 09:11
As I said: if you are using `LAYER_TYPE_SOFTWARE` you need to disable that. If you aren't using `LAYER_TYPE_SOFTWARE`, please provide more details about your environment, i.e. the device this happens on an the Android version.

**Comment by maheshsuthar93** [comment] 2018-08-20 09:40
I ma facing this issue in all devices like Samsung S6,Samsung A5 etc...

**Comment by maheshsuthar93** [comment] 2018-08-20 09:44
![device-2018-08-20-151335](https://user-images.githubusercontent.com/11189023/44333197-c3f7b380-a48b-11e8-8520-2e342fc0d9b8.png)

**Comment by maheshsuthar93** [comment] 2018-08-20 09:45
![device-2018-08-20-151335](https://user-images.githubusercontent.com/11189023/44333236-deca2800-a48b-11e8-84bd-6950aadbe92b.png)

**Comment by maheshsuthar93** [comment] 2018-08-20 09:51
I have loaded image using Picasso.

**Comment by maheshsuthar93** [comment] 2018-08-20 11:03
**From Xml File:**
<de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/image_profile"
                android:layout_width="120dp"
                android:layout_height="120dp"
                android:layout_alignParentTop="true"
                android:layout_centerHorizontal="true"
                android:src="@drawable/large_profile_placeholder"
                app:civ_border_color="#ffffff"
                app:civ_border_width="1dp" />


**//Using Picasso**
  Picasso.with(mContext).
                    load(MY_URL)
                    .placeholder(R.drawable.large_profile_placeholder)
                    .into(image_profile);

**Comment by Fyb3roptik** [comment] 2018-08-27 21:11
This is happening for me on Android Things using the Raspberry Pi 3. Same setup as maheshsuthar93 software wise

**Comment by Fyb3roptik** [comment] 2018-08-27 21:15
Ok so for me, it loads fine the first time inside of my fragment. Then when I switch to a different Fragment and then back to the original one, that is when the black box appears. And it only appears for facebook profile pictures (jpeg images)

**Comment by hdodenhof** [comment] 2018-09-03 19:14
Does this only happen for images loaded using Picasso?

**Comment by hdodenhof** [comment] 2018-09-04 11:19
Does disabling the memory cache in Picasso change the outcome in any way?

**Comment by Fyb3roptik** [comment] 2018-09-07 16:47
How do we disable cache? There are several examples on their github, but which one do we try?

**Comment by Fyb3roptik** [comment] 2018-09-07 17:16
Ok I tried adding .networkPolicy(NetworkPolicy.NO_CACHE).memoryPolicy(MemoryPolicy.NO_CACHE) and that did fix it!

**Comment by Fyb3roptik** [comment] 2018-09-07 19:29
Ok I spoke too soon. It works better than it did before, but it still gets a black border every now and then

**Comment by maheshsuthar93** [comment] 2018-09-08 02:43
I have implemented all but not works and in samsung device some time it
shows placeholder and image both at a time with unexpected results.

**Comment by Fyb3roptik** [comment] 2018-09-10 16:07
I should also say this is happening in Android Things as well. This is what I am using this library on

**Comment by maheshsuthar93** [comment] 2018-09-14 11:55
![screenshot_1536925825](https://user-images.githubusercontent.com/11189023/45548773-281b5680-b843-11e8-99a3-4ba82a426fc9.png)

**Comment by maheshsuthar93** [comment] 2018-09-14 11:56
I am also facing placeholder issue like above in some devices its showing also placeholder with cut edges.

**Comment by hdodenhof** [comment] 2018-09-25 06:58
I'm sorry for the delay, work keeps me quite busy days. Unfortunately I can't reproduce any of the issues with the devices I have at hand. It's very likely that the root cause is an issue with the image decoder on some devices, i.e. nothing that can be fixed in this library. I might be able to add a workaround but I would first need to be able to reproduce the issue.

Can you provide a minimal running sample app that shows these issues together with information on the device you're having this issues on, its Android version, etc.?

**Comment by hdodenhof** [comment] 2019-04-22 12:40
Not much I can do without the requested details.

**Closed by hdodenhof** 2019-04-22 12:40 UTC
