### ISSUE TITLE
2 CircleImageView's problem:1 civ in NavigationView, 1civ in Fragment will show black background

### ISSUE THREAD

**Issue by JackyWang114** [hdodenhof/CircleImageView#97] opened 2015-12-09 17:00 UTC
First Thanks for you project ( . )T( . )

My issue is when i use civ in NavigationView and Fragment, if the NavigationView slide out, the 2civs show black background.

my phone is xiaomi note..

**Comment by hdodenhof** [comment] 2016-01-30 11:00
Duplicate of #31.

**Closed by hdodenhof** 2016-01-30 11:00 UTC
