### ISSUE TITLE
Image looks square

### ISSUE THREAD

**Issue by jatalepallavi** [hdodenhof/CircleImageView#197] opened 2017-05-05 11:26 UTC
![selection_001](https://cloud.githubusercontent.com/assets/28438498/25743756/82d43a4c-3185-11e7-9a0c-1b47416fafe8.png)

See the image is circular but its corner shows background view.
Please help

**Comment by raiarainne** [comment] 2017-07-02 16:03
I faced sameissue with you now.
Did you solved this issue?

**Comment by joaquinTop** [comment] 2017-07-03 18:46
I am facing same issue, any solution?

**Comment by raiarainne** [comment] 2017-07-04 14:33
I found the reason of this issue in my case.
This issue was be occurred when i added click event on this image view.
And also i found solution from following link.
https://github.com/hdodenhof/CircleImageView/issues/153
if you check this solution carefully, you will solve your issue.
I hope this will be help you.
Thank you.

**Comment by hdodenhof** [comment] 2017-09-29 13:38
Probably a duplicate of #127. Try using `LAYER_TYPE_HARDWARE` - reopen, if that doesn't help.

**Closed by hdodenhof** 2017-09-29 13:38 UTC
