### ISSUE TITLE
Add shadow to CircleImageView

### ISSUE THREAD

**Issue by anticafe** [hdodenhof/CircleImageView#89] opened 2015-10-25 17:08 UTC
I see there is [a topic in StackOverflow](http://stackoverflow.com/questions/17655264/how-to-add-a-shadow-and-a-border-on-circular-imageview-android) discuss about add shadow to CircularImageView. Could you implement such feature?

**Comment by MiralDesai** [comment] 2015-12-10 11:41
+1 would love this.

**Comment by hdodenhof** [comment] 2016-01-30 10:43
Duplicate of #50.

**Closed by hdodenhof** 2016-01-30 10:43 UTC
