### ISSUE TITLE
fitxy properties Crash app

### ISSUE THREAD

**Issue by rajumark** [hdodenhof/CircleImageView#332] opened 2019-05-09 10:34 UTC

**Comment by cywmm** [comment] 2019-05-15 03:41
I also encountered the same problem.

`Caused by: java.lang.IllegalArgumentException: ScaleType FIT_XY not supported.`

- Android 7.0

**Comment by ramseth001** [comment] 2019-08-06 02:24
#313

**Comment by hdodenhof** [comment] 2019-08-19 14:31
Duplicate of #313.

**Closed by hdodenhof** 2019-08-19 14:31 UTC
