### ISSUE TITLE
Could not find class 'de.hdodenhof.circleimageview.CircleImageView$OutlineProvider'

### ISSUE THREAD

**Issue by mrifqifuady** [hdodenhof/CircleImageView#260] opened 2018-04-05 16:31 UTC
Hi,
I am have an error Could not find class 'de.hdodenhof.circleimageview in my android studio project,
here's my build.gradle settings,
thankyou

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
        applicationId "com.fuad.youtube"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
    implementation 'com.android.support:design:26.+'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation ("com.github.bumptech.glide:glide:4.6.1") {
        exclude group: "com.android.support"
    }
    implementation "com.android.support:support-fragment:26.1.0"
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
```

**Comment by hdodenhof** [comment] 2018-04-06 07:32
Where exactly do you get that error? What's the full stack trace?

**Comment by hdodenhof** [comment] 2018-04-11 17:33
Returning to 2.1 "resolves" this as that version does not have an `OutlineProvider`.

Unfortunately I haven't been able to reproduce the issue. Any more details about your setup / the crashes / the devices you could share?

**Comment by pengfeigao** [comment] 2018-04-14 18:54
@mrifqifuady I have the same problem.At first I thought CircleImageView's problem.But I found another error log message.
```
04-14 17:20:04.784 4805 4805 E dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
```
I found the culprit was resource files.If you have this error message too.You check to see if you use the <ripple></ripple> in the drawable-v21.But there is no file of the same name in the drawable.
I hope I can help you.

**Comment by AntoGeekz** [comment] 2018-05-28 19:45
Hi,

Same problem here, I meet this problem with a emulator on Android API 19 : 

"05-28 19:39:27.991 5048-5048/com.tadaweb.tadamobileapp.v4.debug W/dalvikvm: Unable to resolve superclass of Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider; (2763)
    Link of class 'Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider;' failed
05-28 19:39:27.991 5048-5048/com.tadaweb.tadamobileapp.v4.debug E/dalvikvm: Could not find class 'de.hdodenhof.circleimageview.CircleImageView$OutlineProvider', referenced from method de.hdodenhof.circleimageview.CircleImageView.init
05-28 19:39:27.991 5048-5048/com.tadaweb.tadamobileapp.v4.debug W/dalvikvm: VFY: unable to resolve new-instance 6086 (Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider;) in Lde/hdodenhof/circleimageview/CircleImageView;
05-28 19:39:27.991 5048-5048/com.tadaweb.tadamobileapp.v4.debug D/dalvikvm: VFY: replacing opcode 0x22 at 0x000e
05-28 19:39:27.991 5048-5048/com.tadaweb.tadamobileapp.v4.debug W/dalvikvm: Unable to resolve superclass of Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider; (2763)
    Link of class 'Lde/hdodenhof/circleimageview/CircleImageView$OutlineProvider;' failed
"

The XML :

"<de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/display_image"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:background="@android:color/white"
            android:padding="2dp"
            app:srcCompat="@drawable/usernameicon" />"

I didnt understand your comment @pengfeigao what do you means? Whichs resources?

**Comment by hdodenhof** [comment] 2018-06-05 18:32
@AntoGeekz does this actually cause any problems or is it just about the log output?

**Comment by AntoGeekz** [comment] 2018-06-07 09:31
No crash, but images are not displayed :/

**Comment by hdodenhof** [comment] 2018-06-07 10:48
That's strange. The `logcat` messages are actually expected on API levels < 21 and images should still be displayed. Does it work if you replace `CircleImageView` with a regular `ImageView` and what kind of Drawable are you trying to display? Some snippets (Java / XML) of your setup would also help to look into the issue.

**Comment by AntoGeekz** [comment] 2018-06-07 11:10
Not sorry, I deleted my previous comm', it was a mistake from myself. Actually yes, it works, the image is showed. It's weird because I thought I had another problem but it seems not... all is working even I I have this log.

**Comment by hdodenhof** [comment] 2018-06-07 12:13
Great, I'll close this issue then.

**Closed by hdodenhof** 2018-06-07 12:13 UTC

**Comment by mrifqifuady** [comment] 2018-06-08 00:15
thankyou

**Comment by agueroveraalvaro** [comment] 2019-03-20 13:44
Its simply because you are using android 4.2 or similar, then change to 2.1v
