### ISSUE TITLE
About setImageBitmap()  black is displayed 

### ISSUE THREAD

**Issue by wkchen66** [hdodenhof/CircleImageView#159] opened 2016-10-19 08:09 UTC
about setImageBitmap()  black is displayed outside the circle

bitmap from glide target

**Comment by wkchen66** [comment] 2016-10-19 08:33
Glide.with(getApplication())
                        .load(smallUrl)
                        .asBitmap()
                        .placeholder(R.drawable.ic_default_head)
                        .diskCacheStrategy(DiskCacheStrategy.ALL)//缓存
                        .into(new SimpleTarget<Bitmap>(width, height) {
                            @Override
                            public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                                 mCivMarker.setImageDrawable(markerBitmap);
 }

**Comment by davidgerka** [comment] 2017-05-18 08:10
@wkchen66 hello,I also appear this kind of situation, do you have a solution,Thanks

**Comment by SametAlbayrak** [comment] 2017-06-05 13:20
Also me too have this problem, the solution isn't found yet?

**Comment by hdodenhof** [comment] 2017-09-29 13:36
Duplicate of #127.

**Closed by hdodenhof** 2017-09-29 13:36 UTC
