### ISSUE TITLE
setting transparent image shows black image 

### ISSUE THREAD

**Issue by VictorTseng** [hdodenhof/CircleImageView#292] opened 2018-09-06 16:53 UTC
I'm also having similar situation here to request for some help.

Ｗhen I set circleimageview, the transparent image shows black somewhere.
how can I change into white color?

**Comment by hdodenhof** [comment] 2018-09-25 07:00
This sounds like a duplicate of #282. If it's not, please provide more details about your issue (i.e. code snippets, screenshots, ...) and reopen this issue. Thanks.

**Closed by hdodenhof** 2018-09-25 07:00 UTC
