### ISSUE TITLE
Black corners on android 5(>=) if set LAYER_TYPE_SOFTWARE

### ISSUE THREAD

**Issue by tttzof351** [hdodenhof/CircleImageView#127] opened 2016-04-29 16:37 UTC
I am try write like this: 
`
compile 'de.hdodenhof:circleimageview:2.0.0'
`

`CircleImageView circleImageView = (CircleImageView) findViewById(R.id.circleImageView);
circleImageView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
circleImageView.setImageResource(R.drawable.vincent_van_gogh_irises);
`

And I see: 
Android 5.1.1 / Sony Xperia
![sony_5 1 1](https://cloud.githubusercontent.com/assets/692328/14922572/01a78900-0e41-11e6-9a9e-8bfd46a159e0.png)

Android 6 .0.1 / Nexus 5
![nexus_5_6 0 1](https://cloud.githubusercontent.com/assets/692328/14922583/15ee9f5c-0e41-11e6-8f7b-38c02c06bc29.png)

But

Android 4.4 / HTC One

![htc_4 4](https://cloud.githubusercontent.com/assets/692328/14922608/37b5d22c-0e41-11e6-8d73-cf8c43c7da1a.png)

**Comment by hdodenhof** [comment] 2016-05-01 15:42
Does this only happen when using `LAYER_TYPE_SOFTWARE`?

**Comment by tttzof351** [comment] 2016-05-04 08:53
Yep, Work fine If I set LAYER_TYPE_HARDWARE or LAYER_TYPE_NONE (or not set at all).

**Comment by nsadiq-radpits** [comment] 2016-05-30 09:46
Same result for me when I use backgound attribute i.e. android:background="@android:color/black". I've tested only on lollipop

**Comment by javierdiaziut** [comment] 2016-11-11 22:42
How did you fix it? I'm facing the same problem

**Comment by tttzof351** [comment] 2016-11-11 22:47
I couldn't quick fix it, so I just refused to use `LAYER_TYPE_SOFTWARE`

**Comment by hdodenhof** [comment] 2017-09-29 13:30
Closing this as duplicate of #108 and for the reasons I mentioned in that issue.

**Closed by hdodenhof** 2017-09-29 13:30 UTC

**Comment by hdodenhof** [comment] 2017-09-29 13:34
Actually, it's probably not a dupe - can confirm it is directly connected to using `LAYER_TYPE_SOFTWARE`, which is not advised anyway.

**Comment by maheshsuthar93** [comment] 2018-08-07 09:26
Yes am i also facing this issue anybody can help me to resolve this issue or provide the link for solution.
