### ISSUE TITLE
why can not use the property of  android:scaleType in xml?

### ISSUE THREAD

**Issue by gmfbilu** [hdodenhof/CircleImageView#148] opened 2016-07-26 08:19 UTC

**Comment by hdodenhof** [comment] 2016-07-27 11:43
This is by design. From the README:
> The ScaleType is always CENTER_CROP and you'll get an exception if you try to change it. This is (currently) by design as it's perfectly fine for profile images.

**Comment by csNewscope** [comment] 2016-08-02 09:46
Could you please disable those limitations? There is no reason why only center crop is allowed. Think of images with an extra wide aspect ratio like a company logo. You have to use fitCenter as scale type to get the full logo inside the circle.
Thanks in advance

**Comment by Jasonnn331** [comment] 2016-08-31 06:59
The scaleType is the critical shortcoming. :(

**Comment by hdodenhof** [comment] 2017-09-29 11:21
While I do understand the requirement for supporting `FIT_CENTER` in case of e.g. company logos, I don't think the result is actually desirable. You would have to know the background color of each logo and set that as the background color for the circle to not have a hard visual break inside the circle. If you still want to go down that road, you can always wrap your `BitmapDrawable` inside a `LayerDrawable` with a `ColorDrawable` as base layer and proper insets on the `BitmapDrawable` on top.

Closing this for now, as there won't be built-in support for more scale types.

**Closed by hdodenhof** 2017-09-29 11:21 UTC
Labels: enhancement
