### ISSUE TITLE
Error inflating class de.hdodenhof.circleimageview.CircleImageView

### ISSUE THREAD

**Issue by dreamguagua** [hdodenhof/CircleImageView#384] opened 2020-06-02 02:20 UTC
user Android viewBind cause:
Binary XML file line #23 in com.nowcoder.app.florida:layout/view_header: Error inflating class de.hdodenhof.circleimageview.CircleImageView

How can I fix it?

**Comment by dreamguagua** [comment] 2020-06-02 02:22
Cause when using ViewBind

**Comment by fanglingfei** [comment] 2020-06-03 03:11
+1，the same problem

**Comment by fanglingfei** [comment] 2020-06-03 03:22
you can fix it by remove : scaleType ,or just use centerCrop

**Comment by hdodenhof** [comment] 2020-06-04 07:24
@dreamguagua please provide the full stack trace of that exception. There's no way to figure out what's wrong without it. Thanks!

**Comment by wahdatjan** [comment] 2020-06-04 15:55
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class de.hdodenhof.circleimageview.CircleImageView
    Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class de.hdodenhof.circleimageview.CircleImageView
    Caused by: java.lang.reflect.InvocationTargetException

**Comment by hdodenhof** [comment] 2020-06-05 09:08
It sure is a possibility, but it could also be a couple of other things. As said before: impossible to tell without a full stackstrace like the attached example. I'll close this until more details are provided.

```
Error inflating class de.hdodenhof.circleimageview.CircleImageView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class de.hdodenhof.circleimageview.CircleImageView
    at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
    at android.app.Activity.setContentView(Activity.java:2166)
    at de.hdodenhof.circleimageview.sample.MainActivity.onCreate(MainActivity.java:11)
    at android.app.Activity.performCreate(Activity.java:6237)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    ... 9 more
Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class de.hdodenhof.circleimageview.CircleImageView
    at android.view.LayoutInflater.createView(LayoutInflater.java:645)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    ... 17 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at android.view.LayoutInflater.createView(LayoutInflater.java:619)
    ... 24 more
Caused by: java.lang.IllegalArgumentException: ScaleType FIT_XY not supported.
    at de.hdodenhof.circleimageview.CircleImageView.setScaleType(CircleImageView.java:143)
    at android.widget.ImageView.<init>(ImageView.java:175)
    at android.widget.ImageView.<init>(ImageView.java:140)
    at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:101)
    at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:97)
```

**Closed by hdodenhof** 2020-06-05 09:08 UTC

**Comment by dreamguagua** [comment] 2020-07-26 14:06
> I think its happenning because of using `scaleType=fitXY` which is not supported by the library

yes !

**Comment by dreamguagua** [comment] 2020-07-26 14:06
> you can fix it by remove : scaleType ,or just use centerCrop

That's ok,Thanks!
