### ISSUE TITLE
How to set background color to circleImageView

### ISSUE THREAD

**Issue by suresh777** [hdodenhof/CircleImageView#43] opened 2015-02-18 10:09 UTC
I have used your class in my app.Actually i wanted to set background to whole circle imageview but it is not working,when i am setting background color it is setting in square shape,but i need in circle imageview only

**Comment by mouse256** [comment] 2015-02-24 16:22
I've created a pull request for this as I needed that myself.

**Comment by hdodenhof** [comment] 2015-02-25 19:03
Duplicate of #26.
I'll look at the PR separately.

**Closed by hdodenhof** 2015-02-25 19:03 UTC
Labels: duplicate
