### ISSUE TITLE
Why CircleImage cann't support HR picture?

### ISSUE THREAD

**Issue by guchuanhang** [hdodenhof/CircleImageView#40] opened 2015-02-06 23:51 UTC
Recently,I'm writing a project.In it ,I need to replace user icon.But When picture come from local picture(HR),it will just show a circle black background
![csdn](https://cloud.githubusercontent.com/assets/8108115/6089470/06a24c8c-ae9e-11e4-8fb4-d0385b66aa95.png)

**Comment by guchuanhang** [comment] 2015-02-06 23:52
I have to append that.When image source from camera .This question doesn't appear!

**Comment by hdodenhof** [comment] 2015-02-25 19:12
Duplicate of #31.

**Closed by hdodenhof** 2015-02-25 19:12 UTC
Labels: duplicate
