### ISSUE TITLE
CircleImageView don't support the  Drawable, it has problem with Glide

### ISSUE THREAD

**Issue by qinjuning** [hdodenhof/CircleImageView#94] opened 2015-11-20 07:15 UTC
Hi hdodenhof :
    I find out that CircleImageView don't work well with  Glide, the thread is <a href="https://github.com/bumptech/glide/issues/757"> Issuse </a> . Will you add the Drawable in ```getBitmapFromDrawable``` method ?  Because of so many project take their own custom Drawable.

**Comment by hdodenhof** [comment] 2016-01-30 11:13
Duplicate of #57. Use `.dontAnimate()` when using Glide, I'll add this to the known limitations.

**Closed by hdodenhof** 2016-01-30 11:13 UTC
