### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by hudan2714** [hdodenhof/CircleImageView#235] opened 2017-10-12 04:22 UTC
java.lang.OutOfMemoryError
                                                                          at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
                                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
                                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:670)
                                                                          at de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable(CircleImageView.java:337)
                                                                          at de.hdodenhof.circleimageview.CircleImageView.initializeBitmap(CircleImageView.java:354)
                                                                          at de.hdodenhof.circleimageview.CircleImageView.setImageDrawable(CircleImageView.java:285)
                                                                          at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:37)
                                                                          at com.bumptech.glide.request.animation.DrawableCrossFadeViewAnimation.animate(DrawableCrossFadeViewAnimation.java:49)
                                                                          at com.bumptech.glide.request.animation.DrawableCrossFadeViewAnimation.animate(DrawableCrossFadeViewAnimation.java:14)
                                                                          at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:75)
                                                                          at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:66)
                                                                          at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:12)
                                                                          at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
                                                                          at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
                                                                          at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
                                                                          at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
                                                                          at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5528)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by hdodenhof** [comment] 2017-10-12 08:32
Duplicate of #195.

**Closed by hdodenhof** 2017-10-12 08:32 UTC
